#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Female_Medium_Prime_PASIFIKA_Head_AnimBP

#include "Basic.hpp"

#include "Fortnite_Base_Head_Export_Skeleton_AnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Female_Medium_Prime_PASIFIKA_Head_AnimBP.Female_Medium_Prime_PASIFIKA_Head_AnimBP_C
// 0x0000 (0x1770 - 0x1770)
class UFemale_Medium_Prime_PASIFIKA_Head_AnimBP_C final : public UFortnite_Base_Head_Export_Skeleton_AnimBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Female_Medium_Prime_PASIFIKA_Head_AnimBP_C">();
	}
	static class UFemale_Medium_Prime_PASIFIKA_Head_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFemale_Medium_Prime_PASIFIKA_Head_AnimBP_C>();
	}
};

}

