#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_Subhead

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Subhead.TextStyle-Subhead_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyle_Subhead_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Subhead_C">();
	}
	static class UTextStyle_Subhead_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Subhead_C>();
	}
};

}

