#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace BP_Shotgun_SG_BFPA { struct FAnimBlueprintGeneratedConstantData; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace Fringe_Plank_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_Ramirez_Fallback_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace Mechanical_Engineer_Female_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Blueprint_Paper_VIM { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_Prime_Skeleton_AnimBlueprint_E { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Medium_Prime_PASIFIKA_Head_AnimBP { struct FAnimBlueprintGeneratedConstantData; }


namespace B_MasterPetAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_Base_Head_Export_Skeleton_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace DBNO_Carried
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace HighTower_Tapas_Axe_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_M_Avg_Player_AnimBlueprint
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace UncleBrollyLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace SwimmingAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Galileo_LobsterLayerAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace MenuScreen_Athena
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace SlidingLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace DBNO_Carried_Simulation
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace B_AnimBP_HightowerRadish
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
